version: '2.0'

# Devrais être utilisé avec docker-compose.yml.
# Monte l'application dans les containers avec des volumes.

services:

  lumen:
    tty: True
    volumes:
      - ./api:/opt/lanadept-website/api
    command: |
      bash -c "bash -s <<EOF
      /opt/wait-for-it/wait-for-it.sh --timeout=0 mariadb:3306 && \
      cd /opt/lanadept-website/api && \
      php artisan key:generate && \
      php artisan migrate --force && \
      php artisan passport:install && \
      php artisan lan:permissions && \
      php artisan lan:roles && \
      php artisan lan:general-admin
      EOF"