version: '2.0'

# Devrais être utilisé avec docker-compose.yml.
# Monte l'application dans les containers avec des volumes.

services:

  nginx:
    ports:
      - ${LANADEPT_API_PORT}:8000
    command: |
      bash -c "bash -s <<EOF
      /opt/wait-for-it/wait-for-it.sh --timeout=0 lumen:9000 && \
      nginx -g \"daemon off;\"
      EOF"
    volumes:
      - ./api/public:/opt/lanadept/lumen/public

  lumen:
    tty: true
    volumes:
      - ./api:/opt/lanadept/lumen:rw

  mariadb:
    ports:
      - "3306:3306"