version: '2.0'

# Définit le service de base de données.
# Utilisé dans :
# - docker-compose.prod.yml: tester que l'environnement de production fonctionne
# - docker-compose.dev.yml: développer et tester l'application

services:

  lumen:
    depends_on:
      - mariadb
    networks:
      - db
    environment:
      DB_DATABASE: lanadept
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: lanadept

  mariadb:
    image: mariadb
    tty: true
    environment:
      MYSQL_USER: lanadept
      MYSQL_PASSWORD: lanadept
      MYSQL_DATABASE: lanadept
      MYSQL_ROOT_PASSWORD: lanadept
      SERVICE_NAME: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db

volumes:
  db_data:

networks:
  db:
    driver: bridge