version: '2.0'

# Création des containers à la base de l'applicationh
# La variable d'environnement LANADEPT_API_PORT dans Makefile doit être définie.

services:
  nginx:
    build: docker/nginx
    networks:
      - lumen

  lumen:
    build: docker/lumen
    image: lanadept-website/lumen
    command: |
      bash -c "bash -s <<EOF
      /opt/wait-for-it/wait-for-it.sh --timeout=0 mariadb:3306 && \
      cd /opt/lanadept/lumen && \
      php artisan key:generate && \
      php artisan migrate && \
      php artisan docker:passport && \
      php artisan lan:permissions && \
      php artisan lan:roles && \
      php artisan lan:general-admin && \
      php-fpm
      EOF"
    networks:
      - lumen

networks:
  lumen:
    driver: bridge
