// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_adept.Migrations
{
    [DbContext(typeof(AdeptContext))]
    [Migration("20220802215823_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_adept.Models.Lan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Lan");
                });

            modelBuilder.Entity("api_adept.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LanId")
                        .HasColumnType("int");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanId");

                    b.HasIndex("SeatId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("api_adept.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("LanId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("LanId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("api_adept.Models.Reservation", b =>
                {
                    b.HasOne("api_adept.Models.Lan", "Lan")
                        .WithMany("Reservations")
                        .HasForeignKey("LanId");

                    b.HasOne("api_adept.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId");

                    b.Navigation("Lan");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("api_adept.Models.Seat", b =>
                {
                    b.HasOne("api_adept.Models.Lan", "Lan")
                        .WithMany("Seats")
                        .HasForeignKey("LanId");

                    b.Navigation("Lan");
                });

            modelBuilder.Entity("api_adept.Models.Lan", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
