name: Front-End

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lan-adept
    steps:
    - uses: actions/checkout@v3
    - run: ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: lan-adept/package-lock.json
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: lan-adept/package-lock.json
        node-version: 16.x
        cache: 'npm'
    - run: ls
    - run: ls lan-adept
    - run: npm ci
    - run: npm run build
